//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msgserver/broadcast_message.proto
namespace msgserver.broadcast_message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgBroadcast_C2S")]
  public partial class CMsgBroadcast_C2S : global::ProtoBuf.IExtensible
  {
    public CMsgBroadcast_C2S() {}
    
    private long _fuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long fuid
    {
      get { return _fuid; }
      set { _fuid = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private long _timems;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"timems", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timems
    {
      get { return _timems; }
      set { _timems = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgBroadcastResp_S2C")]
  public partial class CMsgBroadcastResp_S2C : global::ProtoBuf.IExtensible
  {
    public CMsgBroadcastResp_S2C() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgBroadcast_S2C")]
  public partial class CMsgBroadcast_S2C : global::ProtoBuf.IExtensible
  {
    public CMsgBroadcast_S2C() {}
    
    private long _msgid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long msgid
    {
      get { return _msgid; }
      set { _msgid = value; }
    }
    private long _fuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long fuid
    {
      get { return _fuid; }
      set { _fuid = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private long _timems;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"timems", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timems
    {
      get { return _timems; }
      set { _timems = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}