//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/notify_expand.proto
namespace proto.notify_expand
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HostToOther")]
  public partial class HostToOther : global::ProtoBuf.IExtensible
  {
    public HostToOther() {}
    
    private string _msg = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private int _expand = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"expand", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int expand
    {
      get { return _expand; }
      set { _expand = value; }
    }
    private long _who = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"who", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long who
    {
      get { return _who; }
      set { _who = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}