//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/sync_message.proto
namespace proto.sync_message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMoveInfo")]
  public partial class CMoveInfo : global::ProtoBuf.IExtensible
  {
    public CMoveInfo() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _dtype;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dtype
    {
      get { return _dtype; }
      set { _dtype = value; }
    }
    private int _animID = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"animID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int animID
    {
      get { return _animID; }
      set { _animID = value; }
    }
    private JoinInfo_T _body = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"body", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T body
    {
      get { return _body; }
      set { _body = value; }
    }
    private JoinInfo_T _neck = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"neck", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T neck
    {
      get { return _neck; }
      set { _neck = value; }
    }
    private HandInfo_T _leftHand = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"leftHand", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public HandInfo_T leftHand
    {
      get { return _leftHand; }
      set { _leftHand = value; }
    }
    private HandInfo_T _rightHand = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rightHand", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public HandInfo_T rightHand
    {
      get { return _rightHand; }
      set { _rightHand = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinInfo_T")]
  public partial class JoinInfo_T : global::ProtoBuf.IExtensible
  {
    public JoinInfo_T() {}
    
    private float _pos_x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private float _pos_y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private float _pos_z = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private float _ang_x = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ang_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ang_x
    {
      get { return _ang_x; }
      set { _ang_x = value; }
    }
    private float _ang_y = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ang_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ang_y
    {
      get { return _ang_y; }
      set { _ang_y = value; }
    }
    private float _ang_z = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"ang_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float ang_z
    {
      get { return _ang_z; }
      set { _ang_z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HandInfo_T")]
  public partial class HandInfo_T : global::ProtoBuf.IExtensible
  {
    public HandInfo_T() {}
    
    private JoinInfo_T _palm = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"palm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T palm
    {
      get { return _palm; }
      set { _palm = value; }
    }
    private JoinInfo_T _thumb_1 = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"thumb_1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T thumb_1
    {
      get { return _thumb_1; }
      set { _thumb_1 = value; }
    }
    private JoinInfo_T _thumb_2 = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"thumb_2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T thumb_2
    {
      get { return _thumb_2; }
      set { _thumb_2 = value; }
    }
    private JoinInfo_T _thumb_3 = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"thumb_3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T thumb_3
    {
      get { return _thumb_3; }
      set { _thumb_3 = value; }
    }
    private JoinInfo_T _index_1 = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"index_1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T index_1
    {
      get { return _index_1; }
      set { _index_1 = value; }
    }
    private JoinInfo_T _index_2 = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"index_2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T index_2
    {
      get { return _index_2; }
      set { _index_2 = value; }
    }
    private JoinInfo_T _index_3 = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"index_3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T index_3
    {
      get { return _index_3; }
      set { _index_3 = value; }
    }
    private JoinInfo_T _middle_1 = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"middle_1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T middle_1
    {
      get { return _middle_1; }
      set { _middle_1 = value; }
    }
    private JoinInfo_T _middle_2 = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"middle_2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T middle_2
    {
      get { return _middle_2; }
      set { _middle_2 = value; }
    }
    private JoinInfo_T _middle_3 = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"middle_3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T middle_3
    {
      get { return _middle_3; }
      set { _middle_3 = value; }
    }
    private JoinInfo_T _ring_1 = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"ring_1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T ring_1
    {
      get { return _ring_1; }
      set { _ring_1 = value; }
    }
    private JoinInfo_T _ring_2 = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"ring_2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T ring_2
    {
      get { return _ring_2; }
      set { _ring_2 = value; }
    }
    private JoinInfo_T _ring_3 = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"ring_3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T ring_3
    {
      get { return _ring_3; }
      set { _ring_3 = value; }
    }
    private JoinInfo_T _pinky_1 = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"pinky_1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T pinky_1
    {
      get { return _pinky_1; }
      set { _pinky_1 = value; }
    }
    private JoinInfo_T _pinky_2 = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"pinky_2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T pinky_2
    {
      get { return _pinky_2; }
      set { _pinky_2 = value; }
    }
    private JoinInfo_T _pinky_3 = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"pinky_3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JoinInfo_T pinky_3
    {
      get { return _pinky_3; }
      set { _pinky_3 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CExpressionInfo")]
  public partial class CExpressionInfo : global::ProtoBuf.IExtensible
  {
    public CExpressionInfo() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CPlaytoyInfo")]
  public partial class CPlaytoyInfo : global::ProtoBuf.IExtensible
  {
    public CPlaytoyInfo() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _pos_x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private float _pos_y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private float _pos_z;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private string _none;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"none", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string none
    {
      get { return _none; }
      set { _none = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CShareUrlInfo")]
  public partial class CShareUrlInfo : global::ProtoBuf.IExtensible
  {
    public CShareUrlInfo() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _URL;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"URL", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string URL
    {
      get { return _URL; }
      set { _URL = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSyncInfo")]
  public partial class CSyncInfo : global::ProtoBuf.IExtensible
  {
    public CSyncInfo() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _data;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CNotifyInfo")]
  public partial class CNotifyInfo : global::ProtoBuf.IExtensible
  {
    public CNotifyInfo() {}
    
    private long _fuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long fuid
    {
      get { return _fuid; }
      set { _fuid = value; }
    }
    private long _tuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long tuid
    {
      get { return _tuid; }
      set { _tuid = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _data;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CGetUniqueTool")]
  public partial class CGetUniqueTool : global::ProtoBuf.IExtensible
  {
    public CGetUniqueTool() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _rid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rid
    {
      get { return _rid; }
      set { _rid = value; }
    }
    private int _toolid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"toolid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toolid
    {
      get { return _toolid; }
      set { _toolid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CGetUniqueToolResp")]
  public partial class CGetUniqueToolResp : global::ProtoBuf.IExtensible
  {
    public CGetUniqueToolResp() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CPutUniqueTool")]
  public partial class CPutUniqueTool : global::ProtoBuf.IExtensible
  {
    public CPutUniqueTool() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _rid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rid
    {
      get { return _rid; }
      set { _rid = value; }
    }
    private int _toolid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"toolid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toolid
    {
      get { return _toolid; }
      set { _toolid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CPutUniqueToolResp")]
  public partial class CPutUniqueToolResp : global::ProtoBuf.IExtensible
  {
    public CPutUniqueToolResp() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}