//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msgserver/get_offline_message.proto
namespace msgserver.get_offline_message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CGetOfflineMsg_C2S")]
  public partial class CGetOfflineMsg_C2S : global::ProtoBuf.IExtensible
  {
    public CGetOfflineMsg_C2S() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _maxnum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxnum
    {
      get { return _maxnum; }
      set { _maxnum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OfflineMsg_T")]
  public partial class OfflineMsg_T : global::ProtoBuf.IExtensible
  {
    public OfflineMsg_T() {}
    
    private long _msgid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long msgid
    {
      get { return _msgid; }
      set { _msgid = value; }
    }
    private long _fuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long fuid
    {
      get { return _fuid; }
      set { _fuid = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private long _time = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CGetOfflineMsg_S2C")]
  public partial class CGetOfflineMsg_S2C : global::ProtoBuf.IExtensible
  {
    public CGetOfflineMsg_S2C() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private readonly global::System.Collections.Generic.List<OfflineMsg_T> _msgs = new global::System.Collections.Generic.List<OfflineMsg_T>();
    [global::ProtoBuf.ProtoMember(2, Name=@"msgs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OfflineMsg_T> msgs
    {
      get { return _msgs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CAckOfflineMsg_C2S")]
  public partial class CAckOfflineMsg_C2S : global::ProtoBuf.IExtensible
  {
    public CAckOfflineMsg_C2S() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private long _msgid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msgid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long msgid
    {
      get { return _msgid; }
      set { _msgid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}