//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msgserver/talk_message.proto
namespace msgserver.talk_message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgTalk_C2S")]
  public partial class CMsgTalk_C2S : global::ProtoBuf.IExtensible
  {
    public CMsgTalk_C2S() {}
    
    private long _fuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long fuid
    {
      get { return _fuid; }
      set { _fuid = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _msg = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private long _tuid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"tuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long tuid
    {
      get { return _tuid; }
      set { _tuid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgTalkResp_S2C")]
  public partial class CMsgTalkResp_S2C : global::ProtoBuf.IExtensible
  {
    public CMsgTalkResp_S2C() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private long _time = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgTalk_S2C")]
  public partial class CMsgTalk_S2C : global::ProtoBuf.IExtensible
  {
    public CMsgTalk_S2C() {}
    
    private long _msgid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msgid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long msgid
    {
      get { return _msgid; }
      set { _msgid = value; }
    }
    private long _fuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long fuid
    {
      get { return _fuid; }
      set { _fuid = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _msg = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private long _tuid;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"tuid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long tuid
    {
      get { return _tuid; }
      set { _tuid = value; }
    }
    private long _time = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgAck_C2S")]
  public partial class CMsgAck_C2S : global::ProtoBuf.IExtensible
  {
    public CMsgAck_C2S() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _msgids = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"msgids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> msgids
    {
      get { return _msgids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}